import type { Metadata } from "next";
import "./globals.css";
import localFont from "next/font/local";
import { Toaster } from "sonner";

const yekanbakhFont = localFont({
  // دو بار عقب‌گرد برای خروج از src/app
  src: "../../public/fonts/YekanBakhFaNum-VF.woff",
  variable: "--font-yekanbakh",
  weight: "100 900",
  style: "normal",
  display: "swap",
});

export const metadata: Metadata = {
  title: "RBAC Boilerplate",
  description: "Generated by Amirreza Nouri",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="fa"
      className={`${yekanbakhFont.variable} h-full antialiased`}
      dir="rtl"
    >
      <body className="min-h-full flex flex-col ">
        <Toaster position="bottom-center" richColors  />
        {children}
      </body>
    </html>
  );
}
